# Here we list the names of files available to access them easily in our scripts

- data:
  - raw:
    - public:
      - readme: README.md

    - private:
      - readme: README.md
  - prep:
    - clean:
      - readme: README.md

- reports:
  - notebooks:
    - readme: README.md

- results:
  - files:
    - readme: README.md
  - plots:
    - readme: README.md
